# Generated by Django 4.2 on 2023-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0002_alter_director_bio_alter_pelicula_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='fotoLink',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
