# Generated by Django 4.2 on 2023-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directores', '0003_director_fotolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fotoLink',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
